# Generated by Django 2.0 on 2019-04-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('contact_action', models.CharField(max_length=100, verbose_name='联系方式')),
                ('project_url', models.URLField(verbose_name='项目地址')),
                ('star_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='star的个数')),
                ('follow_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='follow的个数')),
                ('fork_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='fork的个数')),
                ('watch_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='watch的个数')),
                ('start_point', models.IntegerField(blank=True, default=0, null=True, verbose_name='起始位置')),
                ('is_flag', models.BooleanField(default=False, verbose_name='是否执行过')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('order_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='订单价格')),
                ('order_data', models.TextField(blank=True, default='', null=True, verbose_name='数据排序')),
                ('order_payed', models.BooleanField(default=False, verbose_name='支付状态')),
            ],
            options={
                'verbose_name': '商品信息表',
                'verbose_name_plural': '商品信息表',
                'ordering': ['star_num', 'fork_num', 'follow_num'],
            },
        ),
    ]
